# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af1329667804596fa0c2bd9b8f50478d51ed65b622c5fd7414ed796c877d7da647075bfa28f403e33f8cae3c8e718c641ae375b763363e68e8679f2fb6fca04b

test:
  secret_key_base: 2e7b257a09db80a0a1bcf26235abcb6c2a4f4114111f3512aa2bdc321d963189a7974a8c12c01d94cdf22705ace310c9fa57d09c10b82d3acdd352bdcda9d257

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
